"""add_stripe_columns_to_profiles

Revision ID: b8a1d4f4b533
Revises: f1842f2bb1bb
Create Date: 2026-06-03 10:38:50.650574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a1d4f4b533'
down_revision: Union[str, Sequence[str], None] = 'f1842f2bb1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('price_id', sa.String(), nullable=True))
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY users_can_select_own_subscription
        ON users
        FOR SELECT
        USING (auth.uid() = id)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS users_can_select_own_subscription ON users")
    op.drop_column('users', 'price_id')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
